In [6]:
import numpy as np

In [9]:
data = np.loadtxt('inputs/Day2', delimiter = " ", dtype=str)

In [12]:
# The first column is what your opponent is going to play: A for Rock, B for Paper, and C for Scissors.
# The second column, you reason, must be what you should play in response: X for Rock, Y for Paper, and Z for Scissors.

In [24]:
# Convert letters to numbers for lookup
lookup_opponent = {'A':0, 'B':1, 'C':2}
lookup_me = {'X':0, 'Y':1, 'Z':2}

In [25]:
#                       Me > 0(Rock)  1(Paper)  2(Scissors)
#             0(Rock)           3        6            0
# Opponent >  1(Paper)          0        3            6
#             2(Scissors)       6        0            3

In [48]:
# Array, where y = opponent, x = me, and result = number of points

array = np.array([[3,6,0],[0,3,6],[6,0,3]])
print(array)

[[3 6 0]
 [0 3 6]
 [6 0 3]]


In [49]:
sum_points = 0

for row in data:
    
    opponent = lookup_opponent[row[0]]
    me = lookup_me[row[1]]
    
    point = array[opponent][me]
    
    points = point + (me + 1)
    
    #print('{} {} {} {}'.format(opponent, me, point, points))
    
    sum_points += points

In [50]:
print(sum_points)

12645


In [51]:
sum_points = 0

for row in data:
    
    opponent = lookup_opponent[row[0]]
    
    
    me_want = lookup_me[row[1]]
    
    me = np.argmin(abs(array[opponent] - (me_want*3)))
    
    point = array[opponent][me]
    
    points = point + (me + 1)
    
    #print('{} {} {} {}'.format(opponent, me, point, points))
    
    sum_points += points

In [52]:
print(sum_points)

11756
