In [325]:
import numpy as np

file1 = open('inputs/Day8', 'r')
lines = file1.readlines()

In [326]:
# Split string of number into numpy array
trees = np.array([[int(tree) for tree in line[:-1]] for line in lines])

In [327]:
#trees = np.array([[3,0,3,7,3],
#[2,5,5,1,2],
#[6,5,3,3,2],
#[3,3,5,4,9],
#[3,5,3,9,0]])

In [328]:
print(trees)

[[2 3 1 ... 2 3 1]
 [0 0 2 ... 1 2 1]
 [2 2 0 ... 0 3 0]
 ...
 [0 2 0 ... 1 1 1]
 [1 1 0 ... 0 1 2]
 [2 0 2 ... 1 1 2]]


## Part 1

In [329]:
visible = np.zeros_like(trees)
print(visible) 

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [330]:
for y, row in enumerate(trees):
    for x, height in enumerate(row):

        if x == 0 or y == 0 or y == len(trees[:,0])-1 or x == len(trees[0])-1:
            visible[y, x] = 1
            
        else:
            #look left
            if max(trees[y, 0:x]) < height:
                visible[y, x] = 1

            #look right
            if max(trees[y, x+1:]) < height:
                visible[y, x] = 1

            #look up
            if max(trees[0:y, x]) < height:
                visible[y, x] = 1

            #look down
            if max(trees[y+1:, x]) < height:
                visible[y, x] = 1
        

In [331]:
print(visible)

[[1 1 1 ... 1 1 1]
 [1 0 1 ... 0 1 1]
 [1 0 0 ... 0 1 1]
 ...
 [1 1 0 ... 0 0 1]
 [1 1 0 ... 0 0 1]
 [1 1 1 ... 1 1 1]]


In [332]:
print(np.sum(visible))

1662


## Part 2

In [333]:
scenic = np.ones_like(trees)
print(scenic) 

[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


In [334]:
for y, row in enumerate(trees):
    for x, height in enumerate(row):

        if x == 0 or y == 0 or y == len(trees[:,0])-1 or x == len(trees[0])-1:
            scenic[y, x] = 1
            
        else:
            
            # left / right / up / down
            for array in [np.flip(trees[y, 0:x]), trees[y, x+1:], np.flip(trees[0:y, x]), trees[y+1:, x]]:
            
                current_count = 0

                if np.max(array) < height:
                    current_count = len(array)

                else:
                    index = np.where(array >= height)[0][0]
                    current_count = index + 1

                scenic[y,x] *= current_count
                

In [335]:
print(np.max(scenic))

537600


In [336]:
print(scenic)

[[ 1  1  1 ...  1  1  1]
 [ 1  1  8 ...  2  4  1]
 [ 1 12  1 ...  1 12  1]
 ...
 [ 1 30  1 ...  2  2  1]
 [ 1  2  1 ...  1  4  1]
 [ 1  1  1 ...  1  1  1]]
